version: "3.9"
services:
  service1:
    build: ./service1
    image: e1/service1
    ports:
      - "8199:8199"        # only public entry
    depends_on: [service2, storage]
    volumes:
      - vStorage:/app/vstorage               
      - ./vstorage:/host_vstorage            
    networks: [e1net]

  service2:
    build: ./service2
    image: e1/service2
    expose:
      - "8080"              
    volumes:
      - vStorage:/app/vstorage
    networks: [e1net]

  storage:
    build: ./storage
    image: e1/storage
    ports:
      - "5000:5000"          
    volumes:
      - storage_data:/data
    networks:
      - e1net


networks:
  e1net:

volumes:
  vStorage:
  storage_data:
